apiVersion: v1
kind: Service
metadata:
  name: charity-service
spec:
  type: NodePort
  selector:
    app: charity-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080  # Можеш зайти на localhost:30080
